### ISSUE TITLE
Basic workflow

### ISSUE THREAD

**Issue by tienmng** [MD-Studio/charge_assign#9]
Hello,
I would appreciate very much if you could provide some basic steps/command lines to calculate partial charges from an input file.

Thanks and best regards,
Tien Nguyen

**Comment by enitram** [comment]
Hello,

sure, I'm glad to help.

First of all: charge_assign does not do de novo charge computations, but 'puzzles' the charges together from a database of charged molecules. Do you have access to such a database? Otherwise you might want to contact our friends at https://atb.uq.edu.au/

### 1. Setup

Once you have such a database, you can set up charge_assign. You need to convert the molecules to the LGF format. Let's assume your molecules are in the Mol format and you want to use rdkit, you could write a small Python conversion script such as:

```
from rdkit import Chem
from charge.babel import convert_to, convert_from, IOType

rdmol = Chem.MolFromMolFile('path/to/infile.mol')
lgf = convert_to(convert_from(rdmol, IOType.RDKIT), IOType.LGF)
with open('path/to/repodir/outfile.lgf', 'w') as f:
    f.write(lgf)
```

Once you got your molecules in LGF format, you can build a repository:
```
> ./scripts/build_repo -i path/to/repodir -r path/to/repo.zip
```

### 2. Usage

Either setup the Docker charge_assign server (see README), or write a Python script that reads a mol file, assigns charges and writes the charged molecule to another mol file:

```
from rdkit import Chem
from charge.babel import convert_to, convert_from, IOType
from charge.repository import Repository
from charge.chargers import CDPCharger

repo = Repository.read('repo.zip')
charger = CDPCharger(repository=repo)

mol = convert_from(Chem.MolFromMolFile('path/to/uncharged.mol'), IOType.RDKIT)
charger.charge(mol)
with open('path/to/charged.mol', 'w') as f:
    f.write(Chem.MolToMolBlock(convert_to(mol, IOType.RDKIT)))
```

**Comment by tienmng** [comment]
Thank you very much for your help! I appreciate it!

Tien Nguyen
